app = "fci-argy"
primary_region = "eze" # Buenos Aires

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "fci_data"
  destination = "/data"

[env]
  DATABASE_PATH = "/data/database.sqlite"
  PORT = "3000"
